services:
  - type: web
    name: bilmo-llm-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HF_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.0

